version: 0.2

env:
  variables:
    CI_DATABASE_URL: "jdbc:mysql://localhost:3306"
    CI_DATABASE_USER: "root"
    CI_DATABASE_PASSWORD: "rootpassword"
    CI_REDIS_HOST: "localhost"
  parameter-store:
    DEV_DB_URL: "/myapp/datebase_url"
    DEV_DB_USER: "/myapp/datebase_username"
    DEV_DB_PASSWORD: "/myapp/datebase_pwd"
    DEV_MAIL_PASSWORD: "/myapp/email_pwd"
    DEV_MAIL_USERNAME: "/myapp/email_username"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pulling Redis Docker image from ECR...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my_image_store:redis-6.0
      - echo Starting Redis container...
      - docker run -d --name redis -p 6379:6379 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my_image_store:redis-6.0
      - echo Pulling MySQL Docker image from ECR...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my_image_store:mysql-8.0
      - echo Starting MySQL container...
      - docker run -d --name mysql-test-container -e MYSQL_ROOT_PASSWORD=rootpassword -e MYSQL_DATABASE=shiroTest -p 3306:3306 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/my_image_store:mysql-8.0
      - echo Waiting for MySQL to start
      - |
        until docker exec mysql-container mysqladmin ping --host localhost --port 3306 --user=root --password=rootpassword --silent &> /dev/null ; do
          echo -n "." ; sleep 1 ;
        done
      - echo MySQL is up and running
#      - docker logs mysql-container
#      - sudo yum install net-tools -y
#      - sudo netstat -tulnp
#      - docker ps
#      - docker port mysql-container
#      - docker port mysql-container
#      - docker inspect redis | grep -i "networkmode"
#      - docker inspect mysql-container | grep -i "networkmode"
#      - sudo yum install -y nc
#      - nc -zv localhost 6379
#      - nc -zv localhost 3306

  pre_build:
    commands:
      - echo Doing mvn test...
      # 显示从 Parameter Store 获取的变量
      - echo DEV_DB_URL is $DEV_DB_URL
      - echo DEV_DB_USER is $DEV_DB_USER
      - echo DEV_DB_PASSWORD is $DEV_DB_PASSWORD
      - echo DEV_MAIL_PASSWORD is $DEV_MAIL_PASSWORD
      - echo DEV_MAIL_USERNAME is $DEV_MAIL_USERNAME
      # 显示从 设置的变量
      - echo CI_DB_URL is $CI_DATABASE_URL
      - echo CI_DB_USER is $CI_DATABASE_USER
      - echo CI_DB_PASSWORD is $CI_DATABASE_PASSWORD
      - echo CI_REDIS_HOST is $CI_REDIS_HOST
      # 在测试前设置环境变量
      - export DB_URL="$CI_DATABASE_URL"
      - export DB_USERNAME="$CI_DATABASE_USER"
      - export DB_PASSWORD="$CI_DATABASE_PASSWORD"
      - export MAIL_PASSWORD="$DEV_MAIL_PASSWORD"
      - export MAIL_USERNAME="$DEV_MAIL_USERNAME"
      - export REDIS_HOST="$CI_REDIS_HOST"
      - mvn test
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t backend .
      - docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
      - echo Writing image definitions file...
      - pwd
      - printf '{"ImageURI":"%s.dkr.ecr.%s.amazonaws.com/backend:latest"}' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION > imageDetail.json
artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - scripts/**/*
