version: '3'
services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPOSITORY_NAME}:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${DEV_MAIL_USERNAME}
      - MAIL_PASSWORD=${DEV_MAIL_PASSWORD}
      - REDIS_HOST=${DEV_REDIS_HOST}
      - TURNSTILE_SECRET=${TURNSTILE_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - app-network  # 指定网络

  redis:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/my_image_store:redis-6.0
    ports:
      - "6379:6379"
    networks:
      - app-network  # 指定网络

# 定义网络
networks:
  app-network:
    driver: bridge  # 使用 bridge 网络驱动（Docker 默认）
