jwt:
  secret: 2fa959d2db491f91659a3473ffaaded9
turnstile:
  secret: ${TURNSTILE_SECRET}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/shiroTest?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&characterEncoding=utf8&enabledTLSProtocols=TLSv1.2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 替换为你的Gmail账号
    password: ${MAIL_PASSWORD}         # 替换为你的Gmail密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  redis:
    host:  ${REDIS_HOST}
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#ddl-auto：create 每次运行该程序，没有表格会新建表格，表内有数据会清空
#ddl-auto: create-drop 每次程序结束的时候会清空表
#ddl-auto: update 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
#ddl-auto: validate 运行程序会校验数据与数据库的字段类型是否相同，不同会报错
      ddl-auto: none
    show-sql: true

#tomcat端口
server:
  port: 8080
#日志记录级别
logging:
  level:
    org.springframework: info
    org.flywaydb: DEBUG  # Flyway 日志级别
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG  # 如果你使用的是 HikariCP 连接池
#    org.hibernate: DEBUG  # 如果你使用 Hibernate 作为 JPA 提供程序
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari.HikariDataSource: DEBUG
mybatis-plus:
  config-location: classpath:mybatis-config.xml


  # Druid datasource 数据库连接池 默认hikari
#    hikari性能好；druid有面板，方便监控
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 初始化大小
#      initial-size: 5
#      # 最小连接数
#      min-idle: 10
#      # 最大连接数
#      max-active: 20
#      # 获取连接时的最大等待时间
#      max-wait: 60000
#      # 一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
#      filters: stat,wall
#      # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
#      validation-query: SELECT 1
#      # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
#      test-on-borrow: true
#      # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
#      test-on-return: true
#      # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
#      test-while-idle: true
#      # 是否开启 StatViewServlet
#      stat-view-servlet:
#        enabled: true
#        # 访问监控页面 白名单，默认127.0.0.1
#        allow: 127.0.0.1
#        login-username: admin
#        login-password: admin
#      # FilterStat
#      filter:
#        stat:
#          # 是否开启 FilterStat，默认true
#          enabled: true
#          # 是否开启 慢SQL 记录，默认false
#          log-slow-sql: true
#          # 慢 SQL 的标准，默认 3000，单位：毫秒
#          slow-sql-millis: 5000
#          # 合并多个连接池的监控数据，默认false
#          merge-sql: false

