spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shiroTest?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#tomcat端口
server:
  port: 80
#日志记录级别
#logging:
#  level:
#    com.itheima: debug
#    org.springframework: info
#mybatis:
#  # 实体类别名包路径
#  type-aliases-package: shiroTest.entity
#  # 映射文件路径
#  # mapper-locations: classpath:mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl