version: 0.2

env:
  parameter-store:
    DB_URL: "DB_URL"
    DB_USER: "DB_USERNAME"
    DB_PASSWORD: "DB_PASSWORD"
    MAIL_PASSWORD: "MAIL_PASSWORD"
    MAIL_USERNAME: "MAIL_USERNAME"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Pulling Redis Docker image...
      - docker pull redis:latest  # 拉取 Redis 镜像
      - echo Starting Redis container...
      - docker run -d --name redis -p 6379:6379 redis:latest  # 启动 Redis 容器
  pre_build:
    commands:
      - echo Doing mvn test...
      # 显示从 Parameter Store 获取的变量
      - echo DB_URL is $DB_URL
      - echo DB_USER is $DB_USER
      - echo DB_PASSWORD is $DB_PASSWORD
      - echo MAIL_PASSWORD is MAIL_PASSWORD
      - echo MAIL_PASSWORD is MAIL_PASSWORD
      # 在测试前设置环境变量
      - export DATABASE_URL=$DB_URL
      - export DATABASE_USER=$DB_USER
      - export DATABASE_PASSWORD=$DB_PASSWORD
      - export MAIL_PASSWORD=MAIL_PASSWORD
      - export MAIL_PASSWORD=MAIL_PASSWORD
      - mvn test
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - docker build -t backend .
      - docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s.dkr.ecr.%s.amazonaws.com/backend:latest"}' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yaml
